### PR TITLE
add beta tag to version in cargo.toml

### PR DESCRIPTION
**Pull request by knickish**
`v0.2.0` -> `v0.2.0-beta.0`

### CODE REVIEW

**Comment by knickish** [comment]
@not-fl3 do you think it would be better to release a beta version like this and ask for testing in `twiq`, or go straight to `0.2.0` release?

**Comment by not-fl3** [comment]
I like the idea of a beta with a call for test!

**Comment by not-fl3** [comment]
Published on crates! :+1:

**Comment by knickish** [comment]
Thanks!

**Pull request merged**
