### PR TITLE
error in core changes

### PR DESCRIPTION
**Pull request by knickish**
Now that [error in core is stabilizing](https://github.com/rust-lang/rust/issues/103765#issuecomment-2155244052), look at simplifying the feature flags (and making them additive). CI will fail here until it finishes stabilizing, but if we wait for this feature to land it should let us simplify a lot of the code, and only gate features that really rely on `std` (such as hashmaps) behind a `std` feature flag

### CODE REVIEW

**Comment by knickish** [comment]
Looks like this [made it in to the 1.80 milestone](https://github.com/rust-lang/rust/pull/125951#issuecomment-2155311242), so hopefully can merge this after the 2024-07-25 when 1.80 is released

**Comment by knickish** [comment]
There are a lot of changes on master that are not on a crates-io release, might make sense to just merge this and leave the nightly requirement for now

**Comment by knickish** [comment]
@not-fl3 Any thoughts on doing this? Can swap the `no_std` flag for a `std` flag and make it a purely additive feature. Will require nightly to use without the `std` feature until 1.81 releases, but we currently require nightly for no std anyway. After that rust version releases, the nightly requirement can be dropped without a breaking change

**Comment by not-fl3** [comment]
As long as std is on by default, `nanoserde = *` is the only thing required and we don't bump the minimal rust version for a std use case - I am fine with any no_std change, I do not have any strong opinions here

**Pull request merged**
